### ISSUE TITLE
Text window doesn't fill screen on Firefox

### ISSUE THREAD

**Issue by ocdtrekkie** [skygear-demo/skypad#2]
Only about a half-inch of the browser window is usable space. Seems like a CSS issue.

![skypad](https://user-images.githubusercontent.com/4399499/28678081-0a9778b6-72b5-11e7-9f5f-01b11d83c0a0.PNG)

**Comment by david90** [comment]
@ocdtrekkie Thanks for reporting. Fixed, please try again!

**Comment by ocdtrekkie** [comment]
Fix is confirmed.
